name: create standalone

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install dependencies
      run: |
        npm install
        npm prune --production

    - name: Download portable Node.js for Windows
      run: |
        mkdir nodejs
        curl -LO https://nodejs.org/dist/v20.13.1/node-v20.13.1-win-x64.zip
        unzip node-v20.13.1-win-x64.zip -d nodejs
        mv nodejs/node-v20.13.1-win-x64/* nodejs/
        rm -rf nodejs/node-v20.13.1-win-x64 node-v20.13.1-win-x64.zip

    - name: Create run_standalone.bat
      run: |
        echo @echo off > run_standalone.bat
        echo nodejs\\node.exe server.js >> run_standalone.bat
        echo pause >> run_standalone.bat

    - name: Create archive
      run: |
        zip -r evilassspotifyoverlay_standalone.zip . -x ".git/*" ".github/*"

    - name: Install GitHub CLI
      run: sudo apt-get install gh -y

    - name: Create Release with gh CLI
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME="v$(date +'%Y.%m.%d-%H%M%S')"
        gh release create "$TAG_NAME" evilassspotifyoverlay_standalone.zip --title "standalone release $TAG_NAME" --notes "Auto-generated release"
